spring:
  profiles:
    active: default
  datasource:
    url: jdbc:mysql://localhost:3306/ringle
    username: root
    password: kjs38422
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
